### PR TITLE
Typehints

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by robrichards** [comment]
@jaimeperez Is there any reason versions prior to 7.2 need to be dropped? I had pushback not many months ago when I was looking at dropping the 5.x support

**Comment by jaimeperez** [comment]
Hi Rob!

Bumping the minimum supported version gives immediate advantages, like the possibility to add proper type hints all over the place and other new features in the language.

Months ago the situation was worse, since many people was stuck on old versions of PHP (5.x) maintained by Red Hat and other Linux distributions. Nowadays that situation is gone, since there are newer versions of those distros (e.g. RHEL) providing support for PHP 7.2. That means those who were our concern back in the day now finally have a way out, and updating the version of PHP they run is possible.

**Comment by robrichards** [comment]
@jaimeperez I am going to look at putting the 3.x releases into security only and then making this into the 4.x releases. I haven't dug into this code yet but do see its flagged with conflicts. Possible to get those cleaned up? Anything more you plan on adding to this PR or once the conflicts are resolved and I've run thought it, is it good to merge?

**Comment by tvdijen** [comment]
There's a lot in this PR that shouldn't have ended up here... I'll try and come up with a new PR

**Comment by tvdijen** [comment]
Hi @robrichards! I see I never got back to this.. What minimum PHP-version would you like the 4.x release to be at?  I guess 7.2 would be appropriate today? I'd like to introduce Psalm+PHPcs for testing as well if that's okay.. Both are really useful for detecting issues..

**Comment by robrichards** [comment]
@tvdijen 7.1 if possible as that's currently the minimum required. There are still some commercial platforms out there running 7.x with an EOL for them not being until near end of 2020 so trying to keep as much back support as possible.

**Comment by tvdijen** [comment]
Sure! I’ll get to it!!

**Pull request closed without merging**
