### PR TITLE
[composer] Use classmap instead PSR-0

### PR DESCRIPTION
**Pull request by Maks3w**
PSR-0 without namespaces does not offer improvements.

### CODE REVIEW

**Comment by robrichards** [comment]
@Maks3w I'm actually looking at changing it to the PEAR style so wouldn't I be keeping the psr-0 autoloading?

**Comment by Maks3w** [comment]
1. PEAR style is BC Break. People using Composer **MUST** change the class names to use PEAR names

2. If there is any plan over the horizon to use PHP 5.3 namespaces people will need to change the class names again.

The autoload method proposed here fits better with the actual project structure.

**Comment by Maks3w** [comment]
I think for 1.4 we have achieved the objective of split the monolithic file.

There is no need of do more changes in the project structure until PHP version is raised.

**Comment by robrichards** [comment]
Then outside of back porting I'll leave 1.4 alone and 2.x can drop the 5.2 requirement.

**Pull request merged**
