### PR TITLE
Add namespaces

### PR DESCRIPTION
**Pull request by Dashron**
Moves the three main libraries (xmlsecenc, xmlsecuritydsig and xmlsecuritykey) under the `\XMLSecLibs` namespace, and updates all of the tests accordingly.

The base of this PR was the 1.4 branch, so it also includes all changes made in that branch.

Tests are passing, I followed these steps to run the tests:

1. Throw this file in root xmlseclibs directory: https://github.com/php/php-src/blob/master/run-tests.php
2. `php run-tests.php -v -p /usr/bin/php`
3. For each failing test, run the generated .php file (parallel to the .phpt file), and resolve the error message

### CODE REVIEW

**Comment by robrichards** [comment]
@Dashron Thanks. Had to manually merge and just an heads up I plan on changing the tests a little as I think I can get them working without requiring changes from 1.4 branch (just easier for me to maintain is all). Didn't have a chance yet but wanted to get your changes merged so will get to soon

**Comment by robrichards** [comment]
@Dashron Heads up but it appears to be failing in travis for PHP 7. I won't have time till tomorrow to look at that

**Comment by Dashron** [comment]
Cool! As soon as there's a new release I'll move our production code onto this lib, instead of our internally managed variation.

**Comment by Dashron** [comment]
If you run into any weirdness or support cases relating to namespaces feel free to tag me and I'll try to help.

**Comment by Dashron** [comment]
Just saw your earlier message. I'll take a look

**Comment by Dashron** [comment]
Looks like php 7 doesn't like https://github.com/robrichards/xmlseclibs/blob/master/tests/encrypteddata-node-order.phpt#L11, and wants it to just be `use DomDocument;`. The basic idea is all global namespaced classes should be `use <classname>;` without the leading slash.

I'm not sure I'll have time to get to it tonight, but I'll be able to throw together a PR tomorrow morning if you don't beat me to it.

**Comment by Maks3w** [comment]
This PR shouldn't be merged. It was not in a good state.

1. @robrichards Should sync master first
2. The correct way for namespaces it add a prefix with the vendor name. `<vendor>\<project>\<class>...`
3. xmlseclibs file started to don't have sense and should be removed.
4. Does not respect 2 spaces indentation in composer.json

**Comment by robrichards** [comment]
@Maks3w While I know this should have been all done in a branch until it was complete, master wasn't in a state I would have released anyways. I do disagree with the xmlseclibs file. There is no harm in providing an alternate was to use the file. Not everyone uses composer or even autoloading. I will look at fixing 2 and 4 tho.

**Comment by Dashron** [comment]
I thought about `<vendor>\<project>\<class>`, something like `robrichards\xmlseclibs\<class>` but [PS4](http://www.php-fig.org/psr/psr-4/) doesn't actually mandate that. In fact their examples has one that kind of blurs the line (`Zend\Acl`).

The other project I converted to namespaces had a clear vendor, but with an independent developer it gets a little fuzzy. I think that `xmlseclibs` could be a perfectly valid vendor, but honestly have no opinion in the matter. Whatever rob prefers is fine by me, and I'm happy to make another PR for the change.

**Comment by robrichards** [comment]
@Dashron I am pretty neutral on that. Will wait to hear any follow up from @Maks3w tho on this topic

**Comment by Maks3w** [comment]
For me the reason of use a vendor namespace is avoid conflicts with other projects which want to use the same namespace, unless you register xmlseclibs as a trade mark in the whole world.

**Comment by Dashron** [comment]
I agree with the point, but then what vendor name do you suggest? Another person named `robrichards` will still cause a conflict.

**Comment by Maks3w** [comment]
robrichards is already the vendor in composer.json so it's good

**Comment by robrichards** [comment]
I'm fine with changing it to the vendor namespace. @Dashron if you have time can you create a new PR for this otherwise I'll change it when I get some time.

**Comment by Dashron** [comment]
I think I can sneak it in tomorrow. We just need to add `robrichards` to the namespace, and I'll fix the php7 issue.

**Comment by robrichards** [comment]
Php7 should be all set as I fixed the test when I committed the previous namespace change

**Pull request merged**
