### PR TITLE
Enhance php docs

### PR DESCRIPTION
**Pull request by gfaust-qb**
Typos fixed as mentioned in robrichards/xmlseclibs#63. 
PHPDoc-Blocks amended like mentioned in robrichards/xmlseclibs#65 and discussed in robrichards/xmlseclibs#64.
Commits squashed and opened as new PR as discussed and evaluated with @Maks3w in robrichards/xmlseclibs#68.

### CODE REVIEW

**Comment by robrichards** [comment]
Thanks, probably wont be until next week that I have a chance to go through it all. Have been trying to look at it piecemeal

**Comment by gfaust-qb** [comment]
@robrichards I am sorry for the mess, but even squashing it to a single commit (like suggested in #68 by @Maks3w) is ignored by Github, reconstructing the intermediate commits.
It maybe easier to compare only the HEADs.

**Comment by Maks3w** [comment]
@gfaust-qb Do the following

```
git reset a840e7fdbab3d8d80e8f20dfd9a937ceed1faac7
git commit -a -m "Commit message"
git push -f origin Enhance_PHPDocs
```

That will remove all commits but preserving the changes in the working space, then create a commit with all the changes and finally force push (history was rewritten) against your fork

**Comment by gfaust-qb** [comment]
Thanks! I know this from Projects not hosted on Github - but tried to avoid using it because I read the warnings in several discussions. After rethinking it - there is no collaborator working on my fork who will be impeded - I will do this.

**Comment by gfaust-qb** [comment]
Finally I found the right options in PHPStorm7 to do it without having a force-Option for push. Now I know a lot of the Git-Integration of PHPStorm7 :dancer:

**Pull request closed without merging**
