### PR TITLE
add check load public key

### PR DESCRIPTION
**Pull request by RichWeber**
When a certificate is created in the OS Windows, the body of the certificate is written on one line and the function `openssl_get_publickey` returns FALSE.

```
-----BEGIN CERTIFICATE-----
MIIBCgKCAQEAgYxTW5Yj+5QiQtlPMnS9kqQ/HVp+T2KtmvShe68cm8luR7Dampmb...
-----END CERTIFICATE-----
```

Therefore, the signature verification error: `openssl_verify(): supplied key param cannot be coerced into a public key`

But if the body of the certificate split into multiple lines, then everything is working correctly.

```
-----BEGIN CERTIFICATE-----
MIIBCgKCAQEAgYxTW5Yj+5QiQtlPMnS9kqQ/HVp+T2KtmvShe68cm8luR7Dampmb
MIIBCgKCAQEAgYxTW5Yj+5QiQtlPMnS9kqQ/HVp+T2KtmvShe68cm8luR7Dampmb
MIIBCgKCAQEAgYxTW5Yj+5QiQtlPMnS9kqQ/HVp+T2KtmvShe68cm8luR7Dampmb
...
-----END CERTIFICATE-----
```

### CODE REVIEW

**Comment by Maks3w** [comment]
Please add a test

**Comment by RichWeber** [comment]
Done

**Comment by RichWeber** [comment]
Created new request #57

**Comment by RichWeber** [comment]
Created new request #57

**Pull request closed without merging**
