### PR TITLE
allow validation multiple times #108

### PR DESCRIPTION
**Pull request by tmilos**
Fix for #108 that will allow multiple validation of the same instance

### CODE REVIEW

**Comment by tmilos** [comment]
Actually same fix as in #109 ... Merge any of these two

**Comment by tmilos** [comment]
Hello, can somebody merge and release this, so multiple validations can work?

**Comment by sverraest** [comment]
Please merge this.

**Comment by robrichards** [comment]
@tmilos  @sverraest  I will take a look within the next couple of days and see which one of the two I'll merge.

**Comment by sverraest** [comment]
Cool, thanks!

**Pull request merged**
