### PR TITLE
Add robrichards to the namespace as the vendor

### PR DESCRIPTION
**Pull request by Dashron**

### CODE REVIEW

**Comment by Maks3w** [comment]
Update composer.json too

**Comment by Maks3w** [comment]
Please update README.md examples

**Comment by Maks3w** [comment]
Please remove all those leading slashes at the begin of use statements.

**Comment by Dashron** [comment]
Readme is a problem with master. People are likely pulling down a non-namespaced release, and the master readme is shown on github.

**Comment by Maks3w** [comment]
README is part of the same branch there is no exclusions. At most add a link from master to other releases or branches for proper documentation.

Following your idea then you must update README after tag the release

**Comment by Maks3w** [comment]
`XMLSecLibs` should be renamed as `XmlSecLibs` this is for PSR-1 compliant. While this project won't be PSR-1 compliant for a while at least do this change now avoid a BC Break in the future.

**Comment by Maks3w** [comment]
@Dashron Please remove ALL leading slashes on use statements. PHP manual discourage the use of global namespace prefix on use statements

**Comment by Dashron** [comment]
I'm going to defer to @robrichards on the readme, I think changing it at any point pre-release is going to be confusing to users, and in my opinion, not providing confusing, incorrect documentation is way more important than a perfect repo.

Additionally, the first PR was to fix our system, and there was public interest for my code. This second PR was snuck in between other projects, and I'm not sure when I'll have time to continue updates, so feel free to take this PR as a starting point if you need to make the readme, or any additional changes.

**Comment by robrichards** [comment]
@Maks3w I don't see anything in PSR-1 or 2 that defines any specific case usage for the namespace name. I think XMLSecLibs is perfectly legal within the standard. @Dashron I will take care of the readme. As I do have 2 active branches and one just for security and serious issues, I am going to add some info to the readme for folks.

**Comment by Maks3w** [comment]
> Class names MUST be declared in `StudlyCaps`.

Really there is no hard rule about this and it's not clear if there are or not restriction. I just suggest to analyze if do the change now before to release a stable version

**Comment by robrichards** [comment]
I don't think there is as there is definitely a difference between a namespace and a class and namespaces are not called out anywhere. I also have seen a number of projects where they use all lower case for their namespace yet are supposedly compliant. I am planning on keeping it as is yet will definitely make sure to get clarification before making a release tho.

**Pull request merged**
