### PR TITLE
[travis-ci] Setup

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by Maks3w** [comment]
@robrichards Only fails in 5.2 because openssl extension is not available.

We could ommit 5.2 from the test matrix

**Comment by robrichards** [comment]
@Maks3w May need to drop the 5.2 support for Travis as it looks like their 5.2 doesn't include openssl support

**Comment by Maks3w** [comment]
You could exclude those tests from the run if you want and reintroduce the version in the test matrix

**Comment by Maks3w** [comment]
@robrichards done

**Pull request merged**
