### PR TITLE
Add Composer support

### LINKED ISSUE #25: Add composer.json
```
What steps will reproduce the problem?
1. use composer to include your library e.g. with a TYPO3.FLOW project
2. get Exception about missing package
3. add composer.json
4. runs

I used the tar version you provide as download

example composer.json

{
    "name": "robrichards/xmlseclibs",
    "description": "RobRichards XMLSecLibs",
    "license": "Custom",
    "authors": [
        {
            "name": "Rob Richards",
            "email": "your mailadress"
        }
    ],
}

this way i can include your library using these lines in my composer.json

{
...
	"repositories": [
		{
			"type": "composer",
			"url": "https://raw.github.com/kaystrobach/simplesamlphp-composer/master/"
		}, {
			"type": "package",
			"package": {
				"name": "robrichards/xmlseclibs",
				"version": "1.3.1",
				"dist": {
					"url": "https://xmlseclibs.googlecode.com/files/xmlseclibs-1.3.1.tar.gz",
					"type": "tar"
				},
				"autoload": {
					"files": ["xmlseclibs.php"]
				}
			}
		}
	],
...
}

if you would also register on packagist.org and use tags in your svn we could 
use the short form instead ;)

Thank you so much.
Kay
```

Original issue reported on code.google.com by `kay.stro...@gmail.com` on 19 Mar 2014 at 12:16

### PR DESCRIPTION
**Pull request by Maks3w**
Added Composer definition package.

https://getcomposer.org/

Close #25

### CODE REVIEW

**Comment by Maks3w** [comment]
Next steps:

Publish the package in packagist.org https://packagist.org/packages/submit

Create a GIT tag with a new release version. https://github.com/robrichards/xmlseclibs/releases/new

**Comment by robrichards** [comment]
Thanks. I am seeing if there are any other low hanging fruit issues that I can include before I create the release

**Comment by Maks3w** [comment]
@robrichards Don't be afraid of release two times. You know be agile.

This is one of the most requested features, until this is not released I can't declare my fork as deprecated.

**Comment by Maks3w** [comment]
@robrichards Don't forget to register the package in packagist.org!!

**Comment by robrichards** [comment]
@Maks3w Should be all set now

**Pull request merged**
